---
- name: Selecting mirror
  ansible.builtin.lineinfile:
    path: /mnt/gentoo//etc/portage/make.conf
    line: GENTOO_MIRRORS="https://mirrors.kernel.org/gentoo/"
    state: present
    insertafter: EOF

- name: Creating Gentoo ebuild repo
  ansible.builtin.file:
    path: /mnt/gentoo/etc/portage/repos.conf
    state: directory

- name: Copying Gentoo repo config
  ansible.builtin.copy:
    remote_src: true
    src: /mnt/gentoo/usr/share/portage/config/repos.conf
    dest: /mnt/gentoo/etc/portage/repos.conf/gentoo.conf

- name: Copying DNS info
  ansible.builtin.copy:
    remote_src: true
    follow: true
    src: /etc/resolv.conf
    dest: /mnt/gentoo/etc/resolv.conf

- name: Mounting /proc
  ansible.posix.mount:
    path: /mnt/gentoo/proc
    src: /proc
    fstype: proc
    state: mounted

- name: Mounting /sys
  ansible.posix.mount:
    path: /mnt/gentoo/sys
    src: /sys
    opts: rbind,rslave
    fstype: sysfs
    state: mounted

- name: Mounting /dev
  ansible.posix.mount:
    path: /mnt/gentoo/dev
    src: /dev
    opts: rbind,rslave
    fstype: devtmpfs
    state: mounted

- name: Mounting /run
  ansible.posix.mount:
    path: /mnt/gentoo/run
    src: /run
    opts: bind,slave
    fstype: tmpfs
    state: mounted

- name: Mounting boot partition if BIOS
  ansible.posix.mount:
    path: /mnt/gentoo/boot
    src: /dev/sda1
    fstype: ext4
    opts: noatime
    state: mounted
    dump: 0
    passno: 2

- name: Mounting Portage TMPDIR on tmpfs
  ansible.posix.mount:
    path: /mnt/gentoo/var/tmp/portage
    src: tmpfs
    opts: rw,uid=portage,gid=portage,mode=775,nosuid,noatime,nodev	
    fstype: tmpfs
    state: mounted
    dump: 0
    passno: 0
