---
- name: Run depclean
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; emerge --depclean'"

- name: Run eclean-dist
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; eclean-dist --deep'"

- name: Run eclean-pkg
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; eclean-pkg --deep'"

- name: Recursively remove directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /mnt/gentoo/var/log
    - /mnt/gentoo/tmp
    - /mnt/gentoo/var/tmp

- name: Zero-fill free space
  ansible.builtin.shell:
    cmd: |
        dd if=/dev/zero of=junk
        sync
        rm junk

- name: Deactivate swap
  ansible.builtin.shell:
    cmd: "swapoff /dev/sda2"

- name: Zero-fill swap partition
  ansible.builtin.shell:
    cmd: "dd if=/dev/zero of=/dev/sda2"

- name: Make swap
  ansible.builtin.shell:
    cmd: "mkswap /dev/sda2"

- name: Cleaning up Stage 3 tarball
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /mnt/gentoo/{{ stage_tarball }}
    - /mnt/gentoo/{{ stage_tarball }}.asc

- name: Unmounting filesystems
  ansible.posix.mount:
    path: /mnt/gentoo/{{ item }}
    state: unmounted
  ignore_errors: true
  with_items:
    - proc
    - sys
    - dev/pts
    - dev/shm
    - dev
    - boot
    - ''
  loop_control:
    label: /mnt/gentoo/{{ item }}
