---
- name: Emerging Grub
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; emerge sys-boot/grub'"

- name: Installing Grub for BIOS
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; grub-install /dev/sda'"

- name: Updating Grub
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; grub-mkconfig -o /boot/grub/grub.cfg'"
