---
- name: Emerging base packages
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; emerge {{ item }}'"
  with_items:
    - app-admin/sysklogd
    - sys-process/cronie
    - sys-apps/mlocate
    - net-misc/chrony
    - sys-fs/e2fsprogs
    - sys-fs/dosfstools

- name: Enabling services
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; rc-update add {{ item }} default'"
  with_items:
    - sysklogd
    - cronie
    - chronyd
    - sshd
