---
- name: Creating boot partition
  community.general.parted:
    device: /dev/sda
    number: 1
    state: present
    align: optimal
    fs_type: ext4
    label: msdos
    flags: [boot]
    part_start: 1MiB
    part_end: 257MiB

- name: Creating ext4 filesystem on boot partition
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sda1

- name: Creating swap partition
  community.general.parted:
    device: /dev/sda
    number: 2
    state: present
    align: optimal
    fs_type: linux-swap
    label: msdos
    part_start: 258MiB
    part_end: 4355MiB

- name: Making swap
  community.general.filesystem:
    fstype: swap
    dev: /dev/sda2

- name: Activating swap
  ansible.builtin.shell:
    cmd: swapon /dev/sda2

- name: Creating / partition
  community.general.parted:
    device: /dev/sda
    number: 3
    state: present
    align: optimal
    fs_type: ext4
    label: msdos
    part_start: 4356MiB
    part_end: -1MiB

- name: Creating ext4 filesystem on / partition
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sda3

- name: Creating / mountpoint
  ansible.builtin.file:
    path: /mnt/gentoo
    state: directory

- name: Mounting / partition
  ansible.posix.mount:
    path: /mnt/gentoo
    src: /dev/sda3
    fstype: ext4
    opts: noatime
    state: mounted
    dump: 0
    passno: 1
