---
- name: Disabling password complexity requirements
  ansible.builtin.lineinfile:
    path: /mnt/gentoo/etc/security/passwdqc.conf
    regexp: '^enforce='
    line: enforce=none

- name: Setting root password
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; echo 'root:vagrant' | chpasswd'"
  no_log: true

- name: Adding vagrant user
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; useradd vagrant'"

- name: Adding vagrant user to groups
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; gpasswd -a vagrant {{ item }}'"
  with_items:
    - users
    - wheel
    - audio

- name: Setting vagrant user password
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; echo 'vagrant:vagrant' | chpasswd'"
  no_log: true

- name: Emerging sudo
  ansible.builtin.shell:
    cmd: "{{ chroot_cmd }} '. /etc/profile; emerge app-admin/sudo'"

- name: Adding sudoers exception for vagrant user
  ansible.builtin.lineinfile:
    path: /mnt/gentoo/etc/sudoers.d/user-account
    line: "vagrant ALL=(ALL) NOPASSWD: ALL"
    create: true

- name: Setting keyboard layout
  ansible.builtin.lineinfile:
    path: /mnt/gentoo/etc/conf.d/keymaps
    regexp: '^keymap='
    line: keymap="us"

- name: Setting hwclock to UTC
  ansible.builtin.lineinfile:
    path: "/mnt/gentoo/etc/conf.d/hwclock"
    regexp: '^clock='
    line: clock="UTC"
