---
name: CI

on: push

jobs:
  build_bionic:
    name: build-ubuntu-bionic
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fix any “Too many open files” errors
        run: sudo launchctl limit maxfiles unlimited

      - name: Validate template
        run: packer validate -syntax-only box-config.pkr.hcl
        working-directory: ${{ github.workspace }}/ubuntu/bionic

      - name: Build box and publish to Vagrant Cloud
        if: ${{ success() }}  
        run: packer build box-config.pkr.hcl
        working-directory: ${{ github.workspace }}/ubuntu/bionic
        env:
          OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
          VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

  build_win2016:
    name: build-windows-2016
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fix any “Too many open files” errors
        run: sudo launchctl limit maxfiles unlimited

      - name: Validate template
        run: packer validate -syntax-only box-config.pkr.hcl
        working-directory: ${{ github.workspace }}/windows/2016

      - name: Build box and publish to Vagrant Cloud
        if: ${{ success() }}  
        run: packer build box-config.pkr.hcl
        working-directory: ${{ github.workspace }}/windows/2016
        env:
          OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
          VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
  
  build_win10:
    name: build-windows-10
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fix any “Too many open files” errors
        run: sudo launchctl limit maxfiles unlimited

      - name: Validate template
        run: packer validate -syntax-only box-config.pkr.hcl
        working-directory: ${{ github.workspace }}/windows/10

      - name: Build box and publish to Vagrant Cloud
        if: ${{ success() }}  
        run: packer build box-config.pkr.hcl
        working-directory: ${{ github.workspace }}/windows/10
        env:
          OBJC_DISABLE_INITIALIZE_FORK_SAFETY: YES
          VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

  notify:
    name: jira-issue
    runs-on: ubuntu-latest
    needs: [build_bionic, build_win10, build_win2016]
    steps:
      - name: Jira login
        uses: atlassian/gajira-login@master
        if: ${{ always() }}
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira issue if success
        uses: atlassian/gajira-create@master
        if: ${{ success() }}   
        with:
          project: PBJ
          issuetype: Build
          summary: |
            Build completed for ${{ github.repository }}
      - name: Create Jira issue if failed
        uses: atlassian/gajira-create@master
        if: ${{ failure() }}  
        with:
          project: PBJ
          issuetype: Build
          summary: |
            Build failed for ${{ github.repository }}
